FGcelulares/ep-joao/config/routes.rb
Rails.application.routes.draw do
  resources :celulares
  resources :users

end

FGcelulares/ep-joao/app/models/celulare.rb
class Celulare < ActiveRecord::Base
end

FGcelulares/ep-joao/app/models/user.rb
class User < ActiveRecord::Base
validates_presence_of :email, :nome, :local, :senha
validates_confirmation_of :senha
end

FGcelulares/ep-joao/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

FGcelulares/ep-joao/app/controllers/celulares_controller.rb
class CelularesController < ApplicationController
  before_action :set_celulares, only: [:show, :edit, :update, :destroy]

  # GET /celulares
  # GET /celulares.json
  def index
    @celulares = Celulare.all
  end

  # GET /celulares/1
  # GET /celulares/1.json
  def show
  end

  # GET /celulares/new
  def new
    @celulare = Celulare.new
  end

  # GET /celulares/1/edit
  def edit
  end

  # POST /celulares
  # POST /celulares.json
  def create
    @celulares = Celulare.new(celulares_params)

    respond_to do |format|
      if @celulares.save
        format.html { redirect_to @celulares, notice: 'Celulares was successfully created.' }
        format.json { render :show, status: :created, location: @celulares }
      else
        format.html { render :new }
        format.json { render json: @celulares.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /celulares/1
  # PATCH/PUT /celulares/1.json
  def update
    respond_to do |format|
      if @celulares.update(celulare_params)
        format.html { redirect_to @celulares, notice: 'Celulares was successfully updated.' }
        format.json { render :show, status: :ok, location: @celulares }
      else
        format.html { render :edit }
        format.json { render json: @celulares.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /celulares/1
  # DELETE /celulares/1.json
  def destroy
    @celulares.destroy
    respond_to do |format|
      format.html { redirect_to celulares_url, notice: 'Celulares was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_celulares
      @celulares = Celulare.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def celulares_params
      params.require(:celulare).permit(:title, :location, :description, :invoke, :active_record)
    end
end

FGcelulares/ep-joao/app/controllers/users_controller.rb
class UsersController < ApplicationController
def new
@user = User.new
end
def create
@user = User.new(params[:user])
if @user.save
redirect_to @user,
notice: 'Cadastro criado com sucesso!'
else
render action: :new
end
end
end

FGcelulares/ep-joao/app/helpers/application_helper.rb
module ApplicationHelper
end

FGcelulares/ep-joao/app/helpers/celulares_helper.rb
module CelularesHelper
end

FGcelulares/ep-joao/app/views/celulares/_form.html.erb
<%= form_for(@celulare) do |f| %>
  <% if @celulare.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@celulare.errors.count, "error") %> prohibited this celulare from being saved:</h2>

      <ul>
      <% @celulare.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :invoke %><br>
    <%= f.text_field :invoke %>
  </div>
  <div class="field">
    <%= f.label :active_record %><br>
    <%= f.text_field :active_record %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

FGcelulares/ep-joao/app/views/celulares/edit.html.erb
<h1>Editing Celulare</h1>

<%= render 'form' %>

<%= link_to 'Show', @celulare %> |
<%= link_to 'Back', celulares_path %>

FGcelulares/ep-joao/app/views/celulares/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Celulares</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Location</th>
      <th>Description</th>
      <th>Invoke</th>
      <th>Active record</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @celulares.each do |celulare| %>
      <tr>
        <td><%= celulare.title %></td>
        <td><%= celulare.location %></td>
        <td><%= celulare.description %></td>
        <td><%= celulare.invoke %></td>
        <td><%= celulare.active_record %></td>
        <td><%= link_to 'Show', celulare %></td>
        <td><%= link_to 'Edit', edit_celulare_path(celulare) %></td>
        <td><%= link_to 'Destroy', celulare, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Celulare', new_celulare_path %>

FGcelulares/ep-joao/app/views/celulares/new.html.erb
<h1>New Celulare</h1>

<%= render 'form' %>

<%= link_to 'Back', celulares_path %>

FGcelulares/ep-joao/app/views/celulares/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @celulares.title %>
</p>

<p>
  <strong>Location:</strong>
  <%= @celulares.location %>
</p>

<p>
  <strong>Description:</strong>
  <%= @celulares.description %>
</p>

<p>
  <strong>Invoke:</strong>
  <%= @celulares.invoke %>
</p>

<p>
  <strong>Active record:</strong>
  <%= @celulares.active_record %>
</p>

<%= link_to 'Edit', edit_celulare_path(@celulares) %> |
<%= link_to 'Back', celulares_path %>

FGcelulares/ep-joao/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FGcelulares</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

FGcelulares/ep-joao/app/views/users/new.html.erb
<h1>Cadastro</h1>
<%= form_for @user do |f| %>
<p>
<%= f.label :nome %> <br />
<%= f.text_field :nome %>
</p>
<p>
<%= f.label :local%> <br />
<%= f.text_field :local %>
</p>
<p>
<%= f.label :email %> <br />
<%= f.text_field :email %>
</p>
<p>
<%= f.label :senha %> <br />
<%= f.password_field :senha %>
</p>
<p>
<%= f.label :senha_confirmation %> <br />
<%= f.password_field senha_confirmation %>
</p>
<p>
<%= f.label :bio %> <br />
<%= f.text_area :bio %>
</p>
<p>
<%= f.submit %>
</p>
<% end %>